INSERT INTO GENRE (name) VALUES ('Horror');
INSERT INTO GENRE (name) VALUES ('Comedy');
INSERT INTO GENRE (name) VALUES ('Action');
INSERT INTO GENRE (name) VALUES ('Romance');
INSERT INTO GENRE (name) VALUES ('SciFi');
INSERT INTO GENRE (name) VALUES ('Fantasy');
INSERT INTO GENRE (name) VALUES ('Thriller');
INSERT INTO GENRE (name) VALUES ('Xrated');
INSERT INTO GENRE (name) VALUES ('Noir');
INSERT INTO GENRE (name) VALUES ('Animated');
INSERT INTO GENRE (name) VALUES ('Adventure');#
INSERT INTO GENRE (name) VALUES ('Mystery');
INSERT INTO GENRE (name) VALUES ('Drama');
INSERT INTO GENRE (name) VALUES ('Western');
INSERT INTO DIRECTOR (name, age) VALUES ('Steven Spielberg', '71');
INSERT INTO DIRECTOR (name, age) VALUES ('George Lukas', '74');
INSERT INTO DIRECTOR (name, age) VALUES ('Michael Bay', '53');
INSERT INTO DIRECTOR (name, age) VALUES ('Quentin Tarantino', '55');
INSERT INTO DIRECTOR (name, age) VALUES ('Joss Whedon', '54');
INSERT INTO ACTOR (name, age) VALUES ('Ryan Reynolds', '42');
INSERT INTO ACTOR (name, age) VALUES ('Robert Downey jr', '53');
INSERT INTO ACTOR (name, age) VALUES ('Jeff Goldblum', '66');
INSERT INTO ACTOR (name, age) VALUES ('Richard Attenborough', '90');
INSERT INTO MOVIE (title, aid, gid, did) VALUES ('Avengers', 1, 1, 1);
INSERT INTO MOVIE (title, aid, gid, did) VALUES ('Deadpool', 1, 1, 1);
INSERT INTO MOVIE (title, aid, gid, did) VALUES ('Jurassic Park', 1, 1, 1);